version: '3'
 
services:

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python3 manage.py migrate && 
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    restart: always
    image: postgres:10-alpine
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine

  celery_worker:
    build:
      context: .
    command: celery -A developsnews worker -l debug
    volumes:
      - ./:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app
    restart: on-failure

  celery_beat:
    build:
      context: .
    command: celery -A developsnews beat -l debug
    volumes:
      - ./:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app
    restart: on-failure